apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  labels:
    {{- include "elk-stack.labels" . | nindent 4 }}
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.elasticPort }}
    protocol: TCP
    targetPort: db
  selector:
    k8s-app: elasticsearch-logging
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  labels:
    k8s-app: kibana-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Kibana"
    {{- include "elk-stack.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.service.kibanaPort }}
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: kibana-logging
---
kind: Service
apiVersion: v1
metadata:
  name: logstash-service
  labels:
    k8s-app: logstash
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    {{- include "elk-stack.labels" . | nindent 4 }}
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: {{ .Values.service.logPort }}
    targetPort: {{ .Values.service.logPort }}
  type: ClusterIP
---
