# RBAC authn and authz
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "elk-stack.labels" . | nindent 4 }}
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.filebeatServiceAccount.name }}
  labels:
    {{- include "elk-stack.labels" . | nindent 4 }}
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.metricbeatServiceAccount.name }}
  labels:
    k8s-app: metricbeat
    {{- include "elk-stack.labels" . | nindent 4 }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
